version: '3'
services:
  frontend:
    build:
      context: ./client
    image: praveenmethraskar/mern-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: praveenmethraskar/mern-backend:latest
    ports:
      - "5000:5000"
