apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: praveenmethraskar/mern-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "MONGO_URI=mongodb://exam-center_mongo_1:27017/exam_center"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
